services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: aspi-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: aspi_db
      POSTGRES_USER: aspi
      POSTGRES_PASSWORD: aspi123
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C.UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init-databases.sql:/docker-entrypoint-initdb.d/init-databases.sql
    networks:
      - aspi_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aspi -d aspi_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: aspi-redis
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: redis123
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass redis123 --appendonly yes
    networks:
      - aspi_network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis123", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  aspi_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local